### ISSUE TITLE
fix sonar 

### ISSUE THREAD

**Issue by balmaster** [balmaster/repo-build#25]

**Comment by balmaster** [comment]
ERROR: Error during SonarQube Scanner execution
org.sonar.squidbridge.api.AnalysisException: Please provide compiled classes of your project with sonar.java.binaries property
	at org.sonar.java.JavaClasspath.init(JavaClasspath.java:59)
	at org.sonar.java.AbstractJavaClasspath.getElements(AbstractJavaClasspath.java:281)
	at org.sonar.java.SonarComponents.getJavaClasspath(SonarComponents.java:141)
	at org.sonar.java.JavaSquid.<init>(JavaSquid.java:83)
